In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.ndim

2

In [5]:
a.shape

(3, 5)

In [6]:
a.size

15

In [7]:
a.dtype.name

'int32'

In [12]:
a.data

In [8]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [11]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [9]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

In [10]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [21]:
np.empty(2) 

array([1.66036238e-135, 8.89265728e+296])

In [26]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])